### ISSUE TITLE
Correct generic way to use into generic class based views

### ISSUE THREAD

**Issue by luzfcb** [treyhunner/django-simple-history#180]
hello, I have some doubts that I could not fix with reading the documentation (is basically how to using this library out of admin):

1- Is there any implementation (view Mixin class) to use this library in conjunction with UpdateView and DetailView and a generic view to revert?
2 - Is there any way to know if a model instance have or does not have a field with HistoricalRecords instance, without previous knowing the field name?
3- If question 2 is yes, how to get a HistoricalRecords field name?
4 - What is the correct way to do the `revert`  (django-reversion has the `revert()` method `version.revision.revert()`)?
5- what is the correct way to undelete (as django-reversion does)?
6- what is the current support [transaction.atomic](https://docs.djangoproject.com/en/1.8/topics/db/transactions/#controlling-transactions-explicitly) ?

**Comment by luzfcb** [comment]
My first attempt: https://gist.github.com/luzfcb/7fcb0618b5397b7f5a40

**Comment by macro1** [comment]
Hi @luzfcb. Thanks for sharing your work with simple-history here.

The history form in the admin is just using the regular update form. The fields [are populated from the `instance` attribute](https://github.com/treyhunner/django-simple-history/blob/1.6.1/simple_history/admin.py#L82) off of the historical model instance for that version.

I don't know of anyone using this in 'generic' views in a generic way. I'm not sure this action would be part of either of those views though.

To get at the history manager attribute dynamically... Unless it becomes part of this library, I think you should make the manager name a class attribute instead of doing this, since the author of the project should be aware of any non-default settings, but `obj._meta.simple_history_manager_attribute` will get you the attribute name off of the non-historical model. Do a `getattr` with that name, and you will have a manager to the history versions relevant to the model or instance you started with. Below you can see this solution is a little magical. (Magic is usually bad.)

```
obj = self.get_object()
historical_obj = getattr(obj, obj._meta.simple_history_manager_attribute).order_by('-history_id').first()
```

You asked about reverting as well. That bit is easy. Just take a historical instance (for example, the one set above as `historical_obj`), get the `instance` attribute and call save on it. Since it's an instance of the original model, with a PK populated to the original instance, it will save over the original, reverting it to that point in time.

```
obj = historical_obj.instance
obj.save()
```

Just keep in mind that if you combine this with other logic in an update view, this new instance is now the 'real' one. Any other instances you may have as returned by `get_object()` or some other way are probably wrong.

I'm on vacation now, but I'll look at this more in two weeks or so. I like the idea, and I'm sure @treyhunner would agree that some simple tools to make history integration in views easier would be a good addition to the library.

**Comment by treyhunner** [comment]
@luzfcb I don't understand all the details (I'm sure I haven't given it as much thought as you have), but I do like the idea of optional view helper mixins.

**Comment by luzfcb** [comment]
my first attempt slightly more complete https://github.com/treyhunner/django-simple-history/pull/184
