### ISSUE TITLE
Using HistoricalRecords in model with StatusField causes AssertionError from model_utils

### ISSUE THREAD

**Issue by levchik** [treyhunner/django-simple-history#190]
When using HistoricalRecords with any of model_utils model mixins everything seems to work just fine. However, when I specify `history = HistoricalRecords()` on a model that has StatusField, like this:

    MONTHES = MONTHES_CHOICES
    month = StatusField(choices_name='MONTHES')
    history = HistoricalRecords()

it gives me: `AssertionError: To use StatusField, the model 'ModelName' must have a MONTHES choices class attribute.`

Not sure if it works if you don't specify `choices_name`, but I've tried to not import MONTHES_CHOICES from another module and insert the Choices instance directly into `MONTHES` variable and had no luck, still got that same exception.

**Comment by macro1** [comment]
Hi @levchik!

This is most likely because django-simple-history is using the StatusField on the historical model as well. The only existing workaround is to either make a mixin with the `MONTHES` attribute or make an abstract model with that attribute and to override the base classes for the historical model. (See ['Change Base Class' under 'Advanced Usage'](https://django-simple-history.readthedocs.org/en/latest/advanced.html#change-base-class-of-historicalrecord-models))

Example:
```
from django.db import models
from model_utils import Choices
from model_utils.fields import StatusField
from simple_history.models import HistoricalRecords


class FooMixin(object):
    MONTHS = Choices('Jan', 'Feb')


class Bar(FooMixin, models.Model):
    month = StatusField(choices_name='MONTHS')
    history = HistoricalRecords(bases=[FooMixin, models.Model])
```

**Comment by levchik** [comment]
Thanks for the help, @macro1 
I guess this can be closed.

**Comment by vgaicuks** [comment]
@macro1, Thank you very much, save my day!
