### ISSUE TITLE
Failed Import (on shell)

### ISSUE THREAD

**Issue by dwasyl** [treyhunner/django-simple-history#215]
I recently upgraded simple_history from 1.6.1 to the current build, and now I'm noticing that whenever I load a django shell, I see an error like this (in the case of a model called Phone:
    Failed to import 'HistoricalPhone' from 'example.core' reason: 'module' object has no attribute 'HistoricalPhone'

I've been trying to track down the error, but the only way to stop it seems to disable the history = HistoricalRecords() (thus disabling the whole thing).

**Comment by macro1** [comment]
I'm sorry @dwasyl, I can't say I've ever seen anything like that before. Do you have something that's dynamically importing all models in the apps? Maybe `--traceback` will give some additional information on what's failing?

**Comment by pymarco** [comment]
I receive this error

`Failed to import 'HistoricalGroup' from 'apps.groups' reason: 'module' object has no attribute 'HistoricalGroup'`

Django Extensions `shell_plus` command dynamically imports all models.

http://django-extensions.readthedocs.io/en/latest/shell_plus.html

I guess it is ok to ignore.

**Comment by dwasyl** [comment]
I was doing a similar mass import when I got all of the errors - after much testing I just learned to ignore and all seems well.

**Comment by kneufeld** [comment]
Sorry to comment on this necro-thread as I'm seeing the same error. When I start django-extension `shell_plus` (and more or less identical results with the plain shell) I see the following errors:

```text
Failed to import 'HistoricalAction' from 'rules' reason: 'module' object has no attribute 'HistoricalAction'
Failed to import 'HistoricalRule' from 'rules' reason: 'module' object has no attribute 'HistoricalRule'
Failed to import 'HistoricalTimeSpan' from 'rules' reason: 'module' object has no attribute 'HistoricalTimeSpan'
from rules import 
from rules.models.action import Action
from rules.models.rule import Rule
from rules.models.timespan import TimeSpan
```

Then when I try to do a query:

```text
In [2]: TimeSpan.history.most_recent()
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-1ecc11f46543> in <module>()
----> 1 TimeSpan.history.most_recent()

/home/kneufeld/.virtualenvs/XXX/local/lib/python2.7/site-packages/simple_history/manager.pyc in most_recent(self)
     42         if not self.instance:
     43             raise TypeError("Can't use most_recent() without a %s instance." %
---> 44                             self.model._meta.object_name)
     45         tmp = []
     46         for field in self.instance._meta.fields:

TypeError: Can't use most_recent() without a HistoricalTimeSpan instance.
```

I'm assuming that HistoricalTimeSpan is a dynamically created class? Is there some special type of import I need to do?

Django v1.9.12
Simple History v1.8.2

Thanks so much. I'm really liking what I've seen so far when I manually query the database.

**Comment by kneufeld** [comment]
Ug. One error is 100% me and for some reason I needed to use the `register()` function instead of the `HistoricalManager`.

The query (2nd issue in previous comment) was that I needed to run the query on a TimeSpan instance and not the class which makes complete and total sense. My bad.

`TimeSpan.objects.all()[0].history.most_recent()` works as expected.

For anybody else getting a similar import error, try using `register()`.

```
# delete: history =  HistoricalRecords()

# after class definition
from simple_history import register
register(TimeSpan, app='<your app name>')
```

Sorry for wasting your time with a pebcak, keep on fighting the good fight.

**Comment by adibo** [comment]
Since the `Failed to import HistoricalGroup` (or any other historical model for that matter) using `shell_plus` from `django-extensions` could be still and issue, here is another way to get rid of the error.

Just make a list of `SHELL_PLUS_DONT_LOAD` in your `settings.py` with the `someapp.somemodel` entries (note: don't use full model path, like: `apps.someapp.somemodel` - this won't work). Example:
```
SHELL_PLUS_DONT_LOAD = [
    'apps.HistoricalGroups'
]
```
More info: http://django-extensions.readthedocs.io/en/latest/shell_plus.html#configuration
Hope that helps!
