### ISSUE TITLE
Querying on all models that implement history?

### ISSUE THREAD

**Issue by mgallagher** [treyhunner/django-simple-history#223]
I'm wanting to build an "event log" of sorts for the end-users of a site I'm working on, and `simple-history` can easily provide us with data on edits, deletes, etc. We have multiple models that use `HistoricalRecords`. Ideally, I want to be able to query all `Historical` objects in a single query sorted by date.

Right now, this is my workaround for an API endpoint with Django REST:

```
def get_queryset(self):
        historical_apps = ContentType.objects.filter(model__contains='historical').values_list('app_label', 'model')
        historical_models = [apps.get_model(*app_and_model) for app_and_model in historical_apps]
        history_query_sets = [historical_model.objects.all() for historical_model in historical_models]
        combined = list(itertools.chain(*history_query_sets))
        return combined
```

If you search for how to combine multiple `QuerySet` objects (from different models) into one, using `itertools.chain` along with coercing into a `list` is usually the recommended route. In our case though, this dataset is going to be large. This also doesn't support smart pagination (i.e. there is no `LIMIT` in the query generated by this), and I have to sort the objects by date manually.

Any ideas on how else I might approach this?

**Comment by macro1** [comment]
Hello @mgallagher:

If this is your primary use case for history tracking, I would actually recommend one of the apps that uses one table for all history within your project, such as [django-reversion](https://django-reversion.readthedocs.io/).

If you want to stay with django-simple-history, you could look into combining the results using a raw SQL query, or using SQLAlchemy, but both of those options sound terrible.

Maybe you could modify the rest endpoint to be specific for certain dates? Like `history/2016/06` would be a list endpoint filtered to this month, and do a full query of the results from the database instead of paginating.

And my final idea, is building an index model for the history changes, which has entries added similar to the django-simple-history models. You could use a post_save signal to add `model_naturalkey`, `history_id`, and `history_date` to a table as an index, which could then be used to get the history entries once paginated.

**Comment by mgallagher** [comment]
Thanks @macro1 for the response! Those are all great suggestions. I managed to get a raw query working perfectly using UNION in Postgres, and I think I'm going to go that route. 😄

**Comment by mgallagher** [comment]
If anyone is curious, I found that combining a custom SQL view with an unmanaged django model worked perfectly. I can access all tracked models as if they were a single model this way, e.g. `CombinedHistoricalRecords.objects.all()`, sorted by date, and it's plenty fast.
