### ISSUE TITLE
Deleting select historical records

### ISSUE THREAD

**Issue by dwasyl** [treyhunner/django-simple-history#313]
Not sure if this is related to the situation raised in #254, but the app had a runaway save problem and created a ton of nearly duplicate historical entries which need to be cleared.

Running a routine that found each of the duplicate historical objects from `Model.history.first().instance`. And then using `.delete()` seems to delete the original record rather than the history record.

Is it possible to do this through the queryset manager?

**Comment by macro1** [comment]
Have you tried `Model.history.first().delete()`? `instance` is a re-constituted _original_ model. Any kind of database work done on `instance` is not done on the history table, it's done on the original.

**Comment by fopina** [comment]
I'm using this app and, initially, I wanted something more "field-oriented" but now I like to have the full info in each historical record.
The only annoying thing is that each`.save()` will create a new record no matter if there was any change...

I'm not sure if there would be a big impact of adding that check (if all `old` fields are already loaded in memory I guess it's ok) but maybe something useful would be a management command to eliminate duplicate records (or django admin action since this is well admin-oriented).

I wouldn't mind having that in crontab to cleanup database (instead of doing the check directly) and it would solve also issues like this one.

Would that be of interest?

**Comment by rossmechanic** [comment]
@fopina exactly – we've had this feature request a few times, but checking for dirty fields on save would definitely be a lot slower. I'm open to having a management command that deletes duplicate records that users can run periodically. Feel free to put up a PR for that.

**Comment by dwasyl** [comment]
@fopina @rossmechanic To clean up a dirty model history I ended up building a function like that, but it was quite messy and I'm sure there are better ways to do it. What I've done in the meantime is had programs check for fields worth saving being changed and otherwise use `save_without_historical_record` (instead of `save`), but a cleanup crontab would be great. Could be quite memory/process intense thugh.
