### ISSUE TITLE
Custom history field names

### ISSUE THREAD

**Issue by joshvillbrandt** [treyhunner/django-simple-history#328]
I'd like to have fields called something like `modified_by` and `modified_at` on both the primary row and on all of the history row.

Two requests:

1. Is there an easy way to get django-simple-history to automatically add the `history_user` and `history_date` fields to the primary row?
2. Is there a way to override the field names to be `modified_by` and `modified_at`?

Note: I did search the [docs](https://django-simple-history.readthedocs.org/) first to no avail!

**Comment by rossmechanic** [comment]
@joshvillbrandt currently there's no way to change the field names on the historical table. 

For you first question, you have two options.
1. Use an attribute on the model in order to pull `history.history_user` and `history.history_date` from the model.
2. Do something similar to what we do [here](https://django-simple-history.readthedocs.io/en/latest/advanced.html#change-user-model) with the user model, where the history table is set from field on the current model. 

For your second question, you cannot override the field names, but you can set attributes if you'd like.
