### ISSUE TITLE
UUID causes first, last, prev_record, next_record to be incorrectly ordered

### ISSUE THREAD

**Issue by nessalc** [treyhunner/django-simple-history#504]
**The Bug**
If history_id is set to use UUID (`history_id_field=models.UUIDField(default=uuid.uuid4)`), `.first()`, `.last()`, `.next_record` and `.prev_record` do not necessarily perform their expected function. Since, by its nature, UUID4 is random, only a fluke would cause these IDs to be in date order.

**To Reproduce**
1. Add `HistoricalRecords` with `history_id_field=models.UUIDField(default=uuid.uuid4)` to a model
2. Create instance of model
3. Edit model two or more times
4. In shell or template, view `h=model.history.first()`
5. `h.prev_record` should not display anything, but `.next_record` and `.prev_record` appear to be based on date, while `.first()` and `.last()` are based on `history_id`.

**Expected behavior**
I would expect the four functions/properties to be related, especially as they are described this way in the documentation [here](https://django-simple-history.readthedocs.io/en/2.6.0/usage.html#getting-previous-and-next-historical-record).

One of the following should be the case:
- `.first()` and `.last()` should be based on `history_date`
- `.prev_record` and `.next_record` should be based on `history_id`
- documentation should be cleared up regarding the uses of these properties/methods.

**Environment:**
 - OS: Windows 7 x64
 - Django Simple History Version: 2.6.0
 - Django Version: 2.1
 - Python Version: 3.7.1
 - Database Version: SQLite3

**Comment by nessalc** [comment]
Okay, I didn't know about the `.earliest()` and `.latest()` methods. I still think the documentation should be cleaned up, but perhaps that's just me.

**Comment by rossmechanic** [comment]
@nessalc thanks for raising this issue. This behavior is expected, but the documentation should be better. `.first()` and `.last()` are the default queryset methods in Django as described [here](https://docs.djangoproject.com/en/2.1/ref/models/querysets/#first). They just return the first (or last) element in a queryset, which is ordered by primary key by default if not specified otherwise. 

`.prev_record` and `.next_record` are `django-simple-history`-specific methods and also perform as expected –> They go to the previous or next record based on `history_date`. 

The documentation there should definitely use `.earliest` and `.latest` instead of `.first()` and `.last()`, as I admit that can be confusing. Feel free to submit a PR updating the docs and I'll merge it.
