### ISSUE TITLE
bulk_update_with_history

### ISSUE THREAD

**Issue by sergiusnick** [treyhunner/django-simple-history#528]
**Problem Statement**
Method "bulk_create_with_history" is a good feature to make INSERT INTO and save history too with only two queries. But updating is common case too. 

**Describe the solution you'd like**
Create method "bulk_update_with_history" (which is similar to "bulk_create_with_history"), that calls model.objects.update

**Describe alternatives you've considered**
For-loop and call "save". It is important, when you need a special pre- or post-processing, but it is n+1 select problem

**Additional context**
It seems to be easy to do. Just change "bulk_create" on "update" in method "bulk_create_with_history"

**Comment by rossmechanic** [comment]
Hi @sergiusnick, thanks! I implemented `bulk_create_with_history` a few months ago and it's definitely a feature I use a lot. At the time, I looked into doing bulk updating, but it's a little more complicated. The `bulk_create_with_history` one is easy because you have all the base instances to pass to the historical manager in order to bulk_create them on the history table. For updating, it's more complicated because `Model.objects.update(...)` doesn't return the updated instances to then bulk_create on the history table (*remember, the history table is insert only, so we'd never perform an update there). If you can think of a good solution, I'm open to it!

**Comment by sergiusnick** [comment]
Hi!
I have released `create_with_bulk_history` in my project, but it uses 3 queries: update for model, select from model and insert to history model in one transaction. Last 2 queries can be combined to one by using `INSERT INTO SELECT...`-sql-statement, but, as I know, it can not be done by django ORM (Am I right?). If one of these solutions is satisfactory, I can write essential tests and open PR.
The other case is when you have an iterable over changed instances. It can be done by 2 queries (bulk update of instances and bulk create of history), but only with https://github.com/aykut/django-bulk-update.

**Comment by sillycube** [comment]
> Hi!
> I have released `update_with_bulk_history` in my project, but it uses 3 queries: update for model, select from model and insert to history model in one transaction. Last 2 queries can be combined to one by using `INSERT INTO SELECT...`-sql-statement, but, as I know, it can not be done by django ORM (Am I right?). If one of these solutions is satisfactory, I can write essential tests and open PR.
> The other case is when you have an iterable over changed instances. It can be done by 2 queries (bulk update of instances and bulk create of history), but only with https://github.com/aykut/django-bulk-update.

In django 2.2, [bulk_update()](https://docs.djangoproject.com/en/2.2/ref/models/querysets/#bulk-update) has been supported without the need of external plugin.

**Comment by rossmechanic** [comment]
If someone wants to add a `bulk_update_with_history` that utilized `bulk_update`, I'd be happy to look at the PR and accept it.

**Comment by jihoon796** [comment]
@rossmechanic done. https://github.com/treyhunner/django-simple-history/pull/650
