### ISSUE TITLE
Documentation - requests for clarification

### ISSUE THREAD

**Issue by d33tah** [treyhunner/django-simple-history#612]
Hi!

Thanks for django-simple-history! I decided to plug it in to my project a couple of months ago and recently had another requirement to do raw SQL queries or handle inter-project dependencies some other way, which prompted me to read the docs more carefully. There are a couple items that I'm still not clear about:

1. A) What's the relationship between *historical$model and *$model tables? In other words: B) is the latest version stored in *$model, *historical$model, or both?
2. The documentation is missing example use cases for many of the features. One that I most care about is "save without a historical record". A) What happens if the tables go out of sync? B) Does anything prevent that if data was modified externally, are there any automatic health recovery procedures? C) Are there any failure modes I should be aware of? Also: D) is there something new I need to be mindful of when doing raw SQL inserts/updates/selects?
3. Why do some people prefer UUID as history_id?

**Comment by rossmechanic** [comment]
Hi @d33tah! I'll go through and answer each question:
1. The latest version is stored in both tables. The base table knows nothing about the historical table, and the historical table inserts a new row with complete model instance data every time an instance is created, updated, or deleted.
2. A) Nothing happens if the tables go out of sync. The historical table is super naive. B) Nothing to prevent data form being modified externally, although we provide a hook that would allow you to take a historical record and write it elsewhere, maybe to an immutable db. C) No failure modes. D) DSH works on a post_save/post_delete hook, meaning that every time a model instance is saved/deleted a signal is sent that DSH hooks onto, and creates a new record in the historical table. Since raw SQL edits the db directly, no signals are sent (DSH is at the application level rather than the db level). Thus, to maintain the history table while doing raw sql inserts/updates, you'll need to also do raw sql inserts on the historical table. 
3. https://tomharrisonjr.com/uuid-or-guid-as-primary-keys-be-careful-7b2aa3dcb439

**Comment by d33tah** [comment]
Thanks @rossmechanic! :) This seems to answer my questions exhaustively.
