### ISSUE TITLE
Problem with custom user and HistoricalRecords

### ISSUE THREAD

**Issue by csarcom** [treyhunner/django-simple-history#85]
Maybe it is a duplicate of #56 

I tried that: https://gist.github.com/csarcom/9934966
and i got this error:
```python
raise ImproperlyConfigured("AUTH_USER_MODEL refers to model '%s' that has not been installed" % settings.AUTH_USER_MODEL)
django.core.exceptions.ImproperlyConfigured: AUTH_USER_MODEL refers to model 'user.CustomUser' that has not been installed
```
If I remove history = HistoricalRecords() from my model History and add register(CustomUser) from simple_history it works... but, is there a way to work with history = HistoricalRecords() instead register() ?

**Comment by macro1** [comment]
Some similar issues have been reported and all resolved using register. Since this has been reported we've also added a [Common Issues](https://django-simple-history.readthedocs.org/en/latest/reference.html) section to the documentation, this case is listed there. Hopefully that will help with finding a solution quickly.
